arch:
  - amd64
  - ppc64le
language: clojure
cache:
  directories:
  - $HOME/.m2
before_script:
  - rm -f test/readme.clj
  - echo y | sudo lein upgrade
  - sudo apt-get install leiningen
addons:
  apt:
    packages: maven

script: lein test-all
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - openjdk11
